alias rails="bundle exec rails"
alias specjour="bundle exec specjour"
alias rspec="bundle exec rspec"
alias rake="bundle exec rake"
alias pickler="bundle exec pickler"
alias guard="bundle exec guard"
